TEAM-WiseOwl/wiseowlFE

- src/App.jsx
- src/Moblie.jsx
- src/component/DropDown.jsx
- src/page/Info.jsx
- src/page/Info/Info.jsx
- src/page/Info/components/infoheader.jsx
> Info1page UI

- src/App.jsx
- src/Moblie.jsx
- src/page/Info/components/infoheader2.jsx
- src/page/Info/infotwo.jsx
- src/routes.jsx
참고사항 
- 과목추가는 input이 아닌 드롭박스 선택으로 변경예정 
- 과목 값 상태관리는 기능구현 단계에서 보강 예정
> Info2 UI , 과목추가 기능 X

- package-lock.json
- package.json
- src/page/Editcourse/Editcourse.jsx
- src/page/Info/Info.jsx
- src/page/Mypage/Mypage.jsx
수강정보 페이지 완성
참고 : 수강정보 추가 모달은 완성 X
> feat : create

- src/page/Info/infotwo.jsx
- 학기 드롭다운에 대한 논의 필요 
- api 연동으로 모달에서 과목창 가져오는 부분 
- 버튼의 페이지 이동 기능
> Info2 page 수정

- src/App.jsx
- src/Moblie.jsx
- src/globalstyle.jsx
- src/page/Info/subjectmodal1.jsx
- src/page/Info/subjectmodal2.jsx
- src/page/Mypage/mainnotice.jsx
- src/page/request.jsx/request.jsx
- src/page/request.jsx/requestaccept.jsx
- src/routes.jsx
> subjectmodal UI 및 새로운 페이지 라우팅

- src/App.jsx
- src/page/Editrequire/EditSecondrequire.jsx
- src/page/Editrequire/components/CheckBar.jsx
1. 기능 완성 목록
졸업 요건 수정 페이지 (본전공/이중전공) 분리
- 이중전공을 위한 새로운 경로 생성
- 본전공 <-> 이중전공 간 이동 가능 (default : 본전공)
졸업 요건 수정 페이지 컴포넌트화
> feat : change

- src/page/Editmypage/Editmypage.jsx
> EditMypage UI

- src/page/Main/Mainpage.jsx
> main 시설 모아보기 연동

- package-lock.json
- package.json
- src/App.jsx
- src/auth/axiosInstance.js
- src/auth/cookie.js
- src/main.jsx
- src/page/Login/GoogleLoginRedirection.jsx
- src/page/Login/Login.jsx
- src/page/Main/Mainpage.jsx
auth 폴더 생성
- cookie.jsx
- axiosInstance.jsx
> Login Api연동

- src/page/Main/Mainpage.jsx
- src/page/Notice/Notice.jsx
- src/page/Notice/NoticeModal.jsx
- 임시 Notice연동 (아직 추가 기능 구현 X)
- main 수정 예정
> notice 연동 임시

- src/page/Main/Mainpage.jsx
- src/page/Notice/Notice.jsx
- src/page/Notice/NoticeModal.jsx
> axios -> axiosInstance 변경 완료

- src/page/Info/infotwo.jsx
- src/page/Info/subjectmodal1.jsx
- src/page/Info/subjectmodal2.jsx
- src/page/Notice/NoticeModal.jsx
- notice page와 notice modal 연동 완료 
- subjectmodal 1, 2 연동 완료
> Notice , subjectmodal1 2 연동 완료

- .gitignore
- package-lock.json
- src/page/Shopping/Shopping.jsx
- src/page/Shopping/components/MenuCard.jsx
- src/page/Shopping/components/MenuCategory.jsx
- src/page/Shopping/components/MenuSelectBar.jsx
shopping 페이지 api 연동 완료
디자인 수정
-  스크롤 바 삭제
- 상단 음식 추천의 크기 수정
- 하단 음식 목록의 장바구니 추가 버튼 위치 수정
> Apishopping

- src/page/Mypage/mainnotice.jsx
- src/page/Shopping/Shopping.jsx
- mainnotice (파일 경로 : src/page/mypage/mainnotice)에 api 연동 완료 
- shopping 페이지에 남아있던 사용되지 않는 컴포넌트, 경로 등 삭제
> feat : api

- src/page/Editrequire/EditSecondrequire.jsx
- src/page/Editrequire/Editrequire.jsx
- src/page/Mypage/Mypage.jsx
커밋이 2번 들어갔는데 문제 없으면 좋겠네요...
-editrequire 페이지, editsecondrequire 페이지 api 연동 완료(get, patch
모두)
- mypage 코드 오류 수정
> Apieditrequire

- src/App.jsx
- src/page/Editcourse/Editcourse.jsx
- src/page/Editcourse/EditcourseModal.jsx
- src/page/Editcourse/EditcourseModal1.jsx
- src/page/Editcourse/EditcourseModal2.jsx
- src/page/Info/Info.jsx
- src/page/Info/infotwo.jsx
- src/page/Mypage/Mypage.jsx
- src/routes.jsx
> css 제외 api연동

- src/page/Editcourse/Editcourse.jsx
> Editcourse 스타일 수정

- src/page/Editrequire/EditSecondrequire.jsx
- src/page/Editrequire/Editrequire.jsx
- src/page/Editrequire/components/CheckBar.jsx
- 이중전공은 외국어 인증 보이지 않게 수정
- margin 값, width, height 값 수정
- '미이수시 ~' 텍스트 화면 가로 정렬
> css 요청대로 수정

- src/page/Editrequire/EditSecondrequire.jsx
- src/page/Main/components/notices.jsx
- src/page/Notice/Notice.jsx
- src/routes.jsx
> EditRequire 이중전공 수정 , 디자인 수정

- src/page/Mypage/components/NoticeItem.jsx
- src/page/Mypage/mainnotice.jsx
- src/page/Shopping/Shopping.jsx
1. 이동 경로 추가
- 쇼핑페이지, mainnotice 페이지 뒤로가기 버튼 클릭시 main으로 이동
- mainnotice에서 개별 알림 클릭시 해당 링크로 이동
2. 디자인 수정
- 회의때 요청한 모든 담당 디자인 수정
> Changedesign1

- src/component/DropDown4.jsx
- src/component/DropDown5.jsx
- src/page/Require.jsx
1. require페이지 css 수정
2. request 드롭다운 고정
3. 길어지는건 ..으로
> require페이지 css 수정

- src/page/Mypage/components/NoticeItem.jsx
1.세부 알림을 읽으면, 읽었다라는 사실을 백엔드에 api로 전달
- 읽었다면, 세부 알림 우측 상단의 dot이 보이지 않게 수정
> Changedesign4

- src/page/Mypage/components/NoticeItem.jsx
1. 세부 알림 내용 클릭시 페이지가 새로고침 되면서 api를 다시 호출하도록 변경
> 페이지 새로고침 추가

- src/page/Mypage/components/NoticeItem.jsx
페이지가 새로고침 되면서, 새창으로 링크 열기가 동작하지 않는 문제 수정
> 알림 페이지 오류 수정

- src/page/Editcourse/Editcourse.jsx
- src/page/Editmypage/Editmypage.jsx
- src/page/Notice/NoticeModal.jsx
- src/page/Notice/components/NoticeHeader.jsx
디자인 및 api 수정 
sum 클릭시 공지사항 페이지 이동
> 디자인 및 api 수정

- src/page/Editmypage/Editmypage.jsx
> api수정사항 반영

- src/page/Editmypage/Editmypage.jsx
- src/page/Main/components/dashboard.jsx
> api 디자인 수정

- src/page/Editcourse/Editcourse.jsx
- src/page/Editrequire/EditSecondrequire.jsx
- src/page/Editrequire/Editrequire.jsx
1. header의 text margin-bottom 값을 수정
2. editcourse의 뒤로가기 버튼이 동작하지 않는 문제 수정
> Changedesign6

- src/App.jsx
- src/main.jsx
1. main.jsx에 BrowserRouter 추가
2. Router 내에서 app.jsx가 실행되도록 변경
> router 오류 해결 (1)

- src/page/Editcourse/Editcourse.jsx
- src/page/Editmypage/Editmypage.jsx
- src/page/Info/infotwo.jsx
- src/page/Main/components/dashboard.jsx
- src/page/Main/components/map.jsx
> 디자인 10차 수정

- src/page/Editcourse/Editcourse.jsx
- src/page/Editmypage/Editmypage.jsx
- src/page/Info/infotwo.jsx
- src/page/Notice/Notice.jsx
> 디자인 11차 수정

- src/page/Editcourse/Editcourse.jsx
- src/page/Main/components/map.jsx
> Fix design11
